# fly.toml app configuration file generated for translator-study on 2023-07-25T03:13:04+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "translator-study"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "nrt"
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
